### ISSUE TITLE
Issues with skulls.freeskulls and skulls.favourite

### ISSUE THREAD

**Issue by BHPirkle** [Tweetzy/Skulls#1]
### **skulls.freeskulls**
Players who have this permission node do receive free skulls, however they are still charged for it if they have the currency (I have it set to items and use sticks) and even if they are not charged it still displays in the chat that they were.

### **skulls.favourite**
Players who have this permission can see the option to right-click to add a skull to their favorites, however upon right-clicking a skull it doesn't actually add it into their favorites.

**Comment by kiranhart** [comment]
Thanks for reporting it. I'll have it fixed with the 1.18 support

**Comment by kiranhart** [comment]
2.5.1 should resolve these issues

**Comment by BHPirkle** [comment]
I continue to have issues with skull favorites. Granting the permission only lets the _option_ to favorite show up in the skull's lore, but it doesn't actually favorite a skull when a player right-clicks one.
