### ISSUE TITLE
Add an option to make the search check category permissions

### ISSUE THREAD

**Issue by Folas1337** [Tweetzy/Skulls#45]
**Describe Feature**
I'd appreciate if the `/skulls search` could respect categories which you have permission to.\\
That way I could not search for food skulls for example while not having permission to that category.

**Additional Information**
I'm not sure if this is even technically possible but I'd definitely appreciate it :) If not, just let me know and I'll also be accepting a "no" for an answer.

**Comment by kiranhart** [comment]
Yea it's possible
