### ISSUE TITLE
Cannot invoke "ca.tweetzy.skulls.api.interfaces.SkullUser.getUUID()" because "this.skullPlayer" is null

### ISSUE THREAD

**Issue by Feniksovich** [Tweetzy/Skulls#8]
**Describe the bug**
Getting `Cannot invoke "ca.tweetzy.skulls.api.interfaces.SkullUser.getUUID()" because "this.skullPlayer" is null` when trying to open any category or perform search with command `/skulls search`.

**To Reproduce**
1. Open the main menu
2. Click to any category
3. Get exception

**Expected behavior**
Actions must not trigger exceptions.

**Server Information (please complete the following information):**
- git-Purpur-1825 (MC: 1.19.2) (the problem may be related to a platform other than the classic spigot)
- Server Jar: https://api.purpurmc.org/v2/purpur/1.19.2/1825/download
- Plugin Version: 3.4.3

**Additional context**
https://pastebin.com/7pgEejfb

**Comment by Quattrolegni** [comment]
how to fix?

**Comment by Feniksovich** [comment]
> how to fix?

Just make sure you have latest verison installed.
